### ISSUE TITLE
Implement as sbt processor?

### ISSUE THREAD

**Issue by waywardmonkeys** [harrah/browse#6]
Any chance of seeing this as an SBT processor instead of a plugin?

**Comment by harrah** [comment]
For what reason?

**Comment by waywardmonkeys** [comment]
Then we wouldn't have to modify a project (in a way that we can't commit or make part of the public sources) to generate the output?

Right now, as I understand it, we have to modify the project invasively to support this and since the plugin isn't in a Maven repo (that I've seen), we can't just push out those changes to the public, so we have to keep a fork of our project files to support this.

Am I wrong?

**Comment by harrah** [comment]
sxr is a compiler plugin and it is build tool agnostic.  You can run scalac from the command line and pass it the option that says that sxr should be used as a compiler plugin.

It is in a repository, as the README indicates.  I've updated it to mention that there is a 0.2.6 version available.  For reference, it is here:
  http://scala-tools.org/repo-releases/org/scala-tools/sxr/sxr_2.8.0/0.2.6/

Also, people do use branches with different project definitions to have a different configuration locally.  With git there is almost no overhead to this.
