### ISSUE TITLE
no links for dotless method calls 

### ISSUE THREAD

**Issue by ritschwumm** [harrah/browse#7]
for dotless method calls, the method name does not become  a link. 
this is caused by process, the "magic method #2" in Browse.scala 
which does not handle  case Apply(fun, args). 

replacing the case by the following code seems to fix the problem:

``` scala
case Apply(fun, args) =>
    // copy of processDefaultSymbol
    if (fun.hasSymbol && !ignore(fun.symbol)) {
        processSymbol(fun, token, source.file.file, links)
    }
```

**Comment by harrah** [comment]
Sorry for the extremely long delay- sxr is barely maintained.  I'll merge the change if you submit a pull request.  Thanks.

**Comment by harrah** [comment]
Fixed at some point and a test exists for it now, so closing.
