### ISSUE TITLE
Can't build with Scala 2.9.0.1/sbt 0.10.0

### ISSUE THREAD

**Issue by yang** [harrah/browse#8]
I'm using Scala 2.9.0.1 and sbt 0.10.0. Any chance of seeing sxr updated for these? sxr is too useful.

<pre>
$ sbt +update +package
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-tools.sbt#boot-app
        confs: [default]
        1 artifacts copied, 0 already retrieved (838kB/15ms)
Getting Scala 2.8.1 (for sbt)...
:: retrieving :: org.scala-tools.sbt#boot-scala
        confs: [default]
        4 artifacts copied, 0 already retrieved (15296kB/25ms)
Getting org.scala-tools.sbt sbt_2.8.1 0.7.4 ...

:: problems summary ::
:::: WARNINGS
                module not found: org.scala-tools.sbt#sbt_2.8.1;0.7.4

        ==== local: tried

          /home/yang/.ivy2/local/org.scala-tools.sbt/sbt_2.8.1/0.7.4/ivys/ivy.xml

          -- artifact org.scala-tools.sbt#sbt_2.8.1;0.7.4!sbt_2.8.1.jar:

          /home/yang/.ivy2/local/org.scala-tools.sbt/sbt_2.8.1/0.7.4/jars/sbt_2.8.1.jar

        ==== Maven2 Local: tried

          file:///home/yang/.m2/repository/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.pom

          -- artifact org.scala-tools.sbt#sbt_2.8.1;0.7.4!sbt_2.8.1.jar:

          file:///home/yang/.m2/repository/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.jar

        ==== typesafe-ivy-releases: tried

          http://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt_2.8.1/0.7.4/ivys/ivy.xml

          -- artifact org.scala-tools.sbt#sbt_2.8.1;0.7.4!sbt_2.8.1.jar:

          http://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt_2.8.1/0.7.4/jars/sbt_2.8.1.jar

        ==== Maven Central: tried

          http://repo1.maven.org/maven2/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.pom

          -- artifact org.scala-tools.sbt#sbt_2.8.1;0.7.4!sbt_2.8.1.jar:

          http://repo1.maven.org/maven2/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.jar

        ==== Scala-Tools Maven2 Repository: tried

          http://scala-tools.org/repo-releases/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.pom

          -- artifact org.scala-tools.sbt#sbt_2.8.1;0.7.4!sbt_2.8.1.jar:

          http://scala-tools.org/repo-releases/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.jar

        ==== Scala-Tools Maven2 Snapshots Repository: tried

          http://scala-tools.org/repo-snapshots/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.pom

          -- artifact org.scala-tools.sbt#sbt_2.8.1;0.7.4!sbt_2.8.1.jar:

          http://scala-tools.org/repo-snapshots/org/scala-tools/sbt/sbt_2.8.1/0.7.4/sbt_2.8.1-0.7.4.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-tools.sbt#sbt_2.8.1;0.7.4: not found

                ::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-tools.sbt#sbt_2.8.1;0.7.4: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/yang/browse/project/boot/update.log for complete log)
Error: Could not retrieve sbt 0.7.4
</pre>

**Comment by yang** [comment]
I'll take that as a no!

**Comment by harrah** [comment]
It was already done and 0.2.7 is in the scala-tools.org repository.

https://github.com/harrah/browse/commits/master

Specificallly,
https://github.com/harrah/browse/commit/7fac67113b67dc871572b41c465e1c9facd0e8d4
and
https://github.com/harrah/browse/commit/12891c93880b24017a5edd4db29540f75adafc54

**Comment by yang** [comment]
Weird, I don't know why I ran the original command I pasted above, but I just tried `git pull; sbt "+ package"` and it works. Thanks.
